<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-linearalgebra-abhisheksharma414/blob/main/linear_algebra_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [3]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

*Write your answer here (double-click to edit this cell)*

When multiplying by matrix A, the x-component of each vector is scaled by 2, and the y-component is scaled by 3. This means the matrix stretches the vector along the x-axis and the y-axis by different factors.

-   `v1 = [1, 0]` becomes `[2, 0]`: Stretched horizontally by a factor of 2.
-   `v2 = [0, 1]` becomes `[0, 3]`: Stretched vertically by a factor of 3.
-   `v3 = [1, 1]` becomes `[2, 3]`: Stretched by 2 along x and 3 along y.
-   `v4 = [-2, 4]` becomes `[-4, 12]`: Stretched by 2 along x and 3 along y.

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.

*Write your answer here (double-click to edit this cell)*

My classmate is incorrect. Matrix multiplication is not just about numerical manipulation; it fundamentally represents geometric transformations in space. As seen in Part (i), multiplying by matrix A caused vectors to stretch along specific axes, which is a clear visual and geometric change, not just an arithmetic one. Matrices can rotate, reflect, shear, and scale vectors, providing a powerful tool for describing complex geometric operations.

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [4]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [10]:
import numpy as np

# Input — added here for self-containment
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])

def transform_vector(matrix, vector):
    transformed_vector = matrix @ vector
    print(f"The x-component is scaled by {matrix[0,0]} and the y-component is scaled by {matrix[1,1]}.")
    return transformed_vector

print("Testing with matrix A and all four vectors:")
print(f"v1 transformed: {transform_vector(A, v1)}")
print(f"v2 transformed: {transform_vector(A, v2)}")
print(f"v3 transformed: {transform_vector(A, v3)}")
print(f"v4 transformed: {transform_vector(A, v4)}")

Testing with matrix A and all four vectors:
The x-component is scaled by 2 and the y-component is scaled by 3.
v1 transformed: [2 0]
The x-component is scaled by 2 and the y-component is scaled by 3.
v2 transformed: [0 3]
The x-component is scaled by 2 and the y-component is scaled by 3.
v3 transformed: [2 3]
The x-component is scaled by 2 and the y-component is scaled by 3.
v4 transformed: [-4 12]


---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [7]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [11]:
similarity_matrix = users @ users.T
display(similarity_matrix)

array([[1.5 , 0.5 , 1.48, 1.  ],
       [0.5 , 1.5 , 0.52, 1.  ],
       [1.48, 0.52, 1.5 , 1.  ],
       [1.  , 1.  , 1.  , 1.  ]])

**What linear algebra concept makes this possible in one line?**


The linear algebra concept that makes computing the full similarity matrix in one line possible is **matrix multiplication (specifically, the dot product)**. When you multiply a matrix by its transpose (`users @ users.T`), each element of the resulting matrix is the dot product of a row vector from the first matrix and a column vector (which was a row vector from the original matrix) from the second matrix. This efficiently computes all pairwise dot products between the user vectors.

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

*Write your answer here (double-click to edit this cell)*

For these specific user vectors, User D's similarity score with User A, User B, and User C *will* be identical when using the raw dot product. This is because User D has equal scores (0.5) across all genres. When calculating the dot product of User D with any other user (e.g., `UserD ⋅ UserA`), it effectively becomes `0.5 * (Sum of UserA's scores)`. As it happens, the sum of scores for User A, User B, and User C are all `2.0` (`0.9+0.1+0.8+0.2 = 2.0`, `0.1+0.9+0.2+0.8 = 2.0`, `0.8+0.2+0.9+0.1 = 2.0`). Therefore, User D's dot product with A, B, and C will all be `0.5 * 2.0 = 1.0`.

In [12]:
user_D = users[3]
# Calculate dot products of User D with all users
sim_D = users @ user_D
print("User D's raw dot product similarity with all users:")
display(sim_D)

User D's raw dot product similarity with all users:


array([1., 1., 1., 1.])

### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

1.  **What is the problem with raw dot products?**
    Raw dot products are sensitive to the **magnitude (length) of the vectors**. A user who gives high scores to many genres (even if their relative preferences are similar to another user) will have a much larger dot product with that other user simply because their vector has a larger magnitude. This can falsely indicate higher similarity between users who merely express stronger preferences overall, rather than having truly aligned tastes. It measures combined intensity rather than similarity in *preference patterns*.

2.  **Construct a specific example using NumPy that demonstrates the flaw.**
    Let's consider `User A = [0.9, 0.1, 0.8, 0.2]` and `User E = [1.8, 0.2, 1.6, 0.4]` (User A's preferences, doubled in intensity). The raw dot product `UserA ⋅ UserE` is `3.0`, while `UserA ⋅ UserA` is `1.5`. This suggests that User A is more similar to User E than to themselves, which is logically flawed. The flaw is that `UserA` and `UserE` have the *exact same preference pattern*, but the raw dot product doesn't reflect this perfect similarity due to the difference in their magnitudes.

3.  **Fix it.**
    The problem can be fixed by **normalizing** the vectors before computing the dot product. This usually means using **cosine similarity**, which divides the dot product by the product of the magnitudes of the vectors. This effectively measures the cosine of the angle between the two vectors, which represents the similarity in their *direction* or *preference pattern*, independent of their magnitude (intensity). After normalization, `cosine_similarity(UserA, UserE)` would correctly be `1.0`, indicating perfect similarity.

In [13]:
import numpy as np

# Define User E based on the hint
user_E = np.array([1.8, 0.2, 1.6, 0.4])

# Original User A
user_A = users[0]
user_B = users[1]

# 1. Demonstrate the flaw with raw dot products
print("--- Raw Dot Product Flaw ---")
print(f"Dot product (User A, User A): {np.dot(user_A, user_A)}")
print(f"Dot product (User A, User E): {np.dot(user_A, user_E)} (User E has same preferences as A, but higher magnitude)")
print(f"Dot product (User A, User B): {np.dot(user_A, user_B)}")
print("\nRaw dot products suggest User A is more similar to E than to itself, which is misleading as E is just A scaled up.")

# 2. Fix it using cosine similarity (normalization)
print("\n--- Normalized Cosine Similarity Fix ---")

def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0.0
    return dot_product / (norm_vec1 * norm_vec2)

print(f"Cosine Similarity (User A, User A): {cosine_similarity(user_A, user_A):.4f}")
print(f"Cosine Similarity (User A, User E): {cosine_similarity(user_A, user_E):.4f}")
print(f"Cosine Similarity (User A, User B): {cosine_similarity(user_A, user_B):.4f}")
print("\nWith cosine similarity, User A and User E correctly show perfect similarity (1.0), as they have the same preference *pattern*.")

--- Raw Dot Product Flaw ---
Dot product (User A, User A): 1.5000000000000002
Dot product (User A, User E): 3.0000000000000004 (User E has same preferences as A, but higher magnitude)
Dot product (User A, User B): 0.5000000000000001

Raw dot products suggest User A is more similar to E than to itself, which is misleading as E is just A scaled up.

--- Normalized Cosine Similarity Fix ---
Cosine Similarity (User A, User A): 1.0000
Cosine Similarity (User A, User E): 1.0000
Cosine Similarity (User A, User B): 0.3333

With cosine similarity, User A and User E correctly show perfect similarity (1.0), as they have the same preference *pattern*.


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

*Write your answer here (double-click to edit this cell)*

After normalizing the vectors and computing cosine similarity:

*   **Which two users are most similar?**
    **User A** and **User C** are the most similar, with a cosine similarity score of approximately **0.9867**. This is very close to 1.0, indicating a strong alignment in their preference patterns.

*   **Does that match your intuition from just reading the vectors?**
    Yes, this matches my intuition. Both User A (`[0.9, 0.1, 0.8, 0.2]`) and User C (`[0.8, 0.2, 0.9, 0.1]`) show high scores for Action and Thriller, and low scores for Romance and Comedy. They both clearly prefer action/thriller genres over romance/comedy. User B, in contrast, prefers romance/comedy, and User D is neutral.

*   **What does it mean in plain language — what do these two users have in common?**
    In plain language, User A and User C have very similar taste profiles. They both strongly enjoy **action** and **thriller** movies, and are not particularly fond of **romance** or **comedy**. They are essentially both 'action/thriller lovers' and would likely enjoy similar movie recommendations.

In [14]:
import numpy as np

# Normalize the user vectors
# Calculate the L2 norm (magnitude) for each user vector
norms = np.linalg.norm(users, axis=1, keepdims=True)
# Divide each user vector by its norm to get unit vectors
normalized_users = users / norms

# Compute the cosine similarity matrix
# This is done by multiplying the normalized_users matrix by its transpose
cosine_similarity_matrix = normalized_users @ normalized_users.T

print("Cosine Similarity Matrix:")
display(cosine_similarity_matrix)

# Find the pair with the highest similarity (excluding self-similarity)
# Fill the diagonal with 0 or -1 to exclude self-similarity
# (or iterate only over upper triangle)
np.fill_diagonal(cosine_similarity_matrix, -1) # Set diagonal to -1 to ignore self-similarity

# Find the indices of the maximum value in the matrix
max_sim_index = np.unravel_index(np.argmax(cosine_similarity_matrix), cosine_similarity_matrix.shape)

# Map indices back to user names
user_labels = ['User A', 'User B', 'User C', 'User D']
most_similar_users = (user_labels[max_sim_index[0]], user_labels[max_sim_index[1]])
max_similarity_score = cosine_similarity_matrix[max_sim_index]

print(f"\nThe two most similar users are {most_similar_users[0]} and {most_similar_users[1]} with a similarity score of {max_similarity_score:.4f}.")

Cosine Similarity Matrix:


array([[1.        , 0.33333333, 0.98666667, 0.81649658],
       [0.33333333, 1.        , 0.34666667, 0.81649658],
       [0.98666667, 0.34666667, 1.        , 0.81649658],
       [0.81649658, 0.81649658, 0.81649658, 1.        ]])


The two most similar users are User A and User C with a similarity score of 0.9867.


---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.